In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
import torch
torch.cuda.is_available()

True

In [1]:
import torch

In [14]:
a=torch.tensor([2,4,6,8])
print(a)
#or
b=[2,3,4,5]
torch.tensor(b)
print(a.numel())
print(a.size())
print(a.ndim)
print(a.shape)
print("\n",a.dtype)


tensor([2, 4, 6, 8])
4
torch.Size([4])
1
torch.Size([4])

 torch.int64


In [37]:
a=torch.ones((2,3),dtype=torch.int64)
b=torch.zeros(2,2,dtype=int)
print(a)
print(b)
c=torch.arange(5,16,2)
print(c)
d=torch.range(5,16,2)
print(c)

print(d[1:4:2])


tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0],
        [0, 0]])
tensor([ 5,  7,  9, 11, 13, 15])
tensor([ 5,  7,  9, 11, 13, 15])
tensor([ 7., 11.])
tensor([[0.5495, 0.6230, 0.8017, 0.4959, 0.0050],
        [0.6091, 0.8250, 0.8253, 0.0823, 0.1876],
        [0.1028, 0.3964, 0.4845, 0.4010, 0.2686]])
tensor([[ 1.3852,  1.9060, -0.6390,  1.6277, -0.7554],
        [ 1.4529, -0.6653,  1.0060,  0.8836, -0.3796],
        [-0.1082,  1.3594, -0.1431,  1.0010,  0.0445]])


/tmp/ipykernel_845/2896689801.py:7: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  d=torch.range(5,16,2)


In [39]:
print(torch.rand(3,5))#the values between 0 to 1
print(torch.randn(3,5))#mixing the positive and negative

tensor([[0.0347, 0.4700, 0.6986, 0.8701, 0.0774],
        [0.8124, 0.2685, 0.0624, 0.7836, 0.0819],
        [0.7376, 0.5967, 0.7557, 0.8631, 0.4844]])
tensor([[-0.7290, -0.5738,  0.0716,  0.2147, -0.7599],
        [-0.0466,  1.1269, -0.2752, -1.4157,  1.7094],
        [ 2.3182, -0.8619, -0.7113, -0.4336, -1.0184]])


In [44]:
a=torch.full((2,3),8)
a

tensor([[8, 8, 8],
        [8, 8, 8]])

In [140]:
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a[1])
print(a[2])
print(a[[2,3]])#this is known as fancy index
print(a[[2]])
print(a[[2,3],2])
print(a[[1,2],[1,2]])



tensor([36, 94, 72, 81])
tensor([24, 56, 79,  3])
tensor([[24, 56, 79,  3],
        [ 1,  2,  4,  5]])
tensor([[24, 56, 79,  3]])
tensor([79,  4])
tensor([94, 79])


In [125]:
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a[[0,1,2],[1,2,3]])
print(a[2:4,2:4])
print(a[2:,2:])
print(a[1:3,1:3])
print(a[-3:-1,-3:-1])
print(a[0:4,0:1])

tensor([36, 72,  3])
tensor([[79,  3],
        [ 4,  5]])
tensor([[79,  3],
        [ 4,  5]])
tensor([[94, 72],
        [56, 79]])
tensor([[94, 72],
        [56, 79]])
tensor([[18],
        [36],
        [24],
        [ 1]])


In [80]:
# mathematical operations

In [ ]:
# add
# subtract
# divide
# multiply

In [101]:
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
print(torch.add(a,b))
print(torch.sum(a))#sum doesnt take two arguments
print(torch.subtract(a,b))
print(torch.multiply(a,b))
print(torch.divide(a,b))
print(torch.mul(a,b))
print(torch.sub(a,b))
print(torch.div(a,b))


tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor(21)
tensor([[-6, -6, -6],
        [-6, -6, -6]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[-6, -6, -6],
        [-6, -6, -6]])
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])


In [126]:
a=torch.tensor([[1,2,53,4,5,6],[7,8,9,10,11,12]])
print(a)
print(torch.flip(a,dims=[1]))
print(torch.flip(a,dims=[0]))
print(torch.argmax(a))
print(a.argmax())
print(torch.argmin(a))
print(a.argmin())
print(a.max())
print(a.min())


tensor([[ 1,  2, 53,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
tensor([[ 6,  5,  4, 53,  2,  1],
        [12, 11, 10,  9,  8,  7]])
tensor([[ 7,  8,  9, 10, 11, 12],
        [ 1,  2, 53,  4,  5,  6]])
tensor(2)
tensor(2)
tensor(0)
tensor(0)
tensor(53)
tensor(1)


In [135]:
ai=torch.tensor([40,60,30,70,95])
print(ai>=70)
print(ai[ai>=70])

tensor([False, False, False,  True,  True])
tensor([70, 95])


In [139]:
ai=torch.tensor([40,60,30,75,95])
print(ai[ai>=60])
print(ai>=60)
print(ai>35)
print(ai[ai>35])

tensor([60, 75, 95])
tensor([False,  True, False,  True,  True])
tensor([ True,  True, False,  True,  True])
tensor([40, 60, 75, 95])
